/*
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRuleDSLScopeProvider extends DelegatingScopeProvider {
}
