/**
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.validation;

import de.shashwat.xtext.homeauto.validation.AbstractRuleDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RuleDSLValidator extends AbstractRuleDSLValidator {
}
