/*
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class RuleDSLWebModule extends AbstractRuleDSLWebModule {
}
