/**
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.ui.contentassist;

import de.shashwat.xtext.homeauto.ui.contentassist.AbstractRuleDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RuleDSLProposalProvider extends AbstractRuleDSLProposalProvider {
}
