/**
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.shashwat.xtext.homeauto.RuleDSLRuntimeModule;
import de.shashwat.xtext.homeauto.RuleDSLStandaloneSetup;
import de.shashwat.xtext.homeauto.ide.RuleDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RuleDSLIdeSetup extends RuleDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    RuleDSLRuntimeModule _ruleDSLRuntimeModule = new RuleDSLRuntimeModule();
    RuleDSLIdeModule _ruleDSLIdeModule = new RuleDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_ruleDSLRuntimeModule, _ruleDSLIdeModule));
  }
}
