/**
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.ide;

import de.shashwat.xtext.homeauto.ide.AbstractRuleDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RuleDSLIdeModule extends AbstractRuleDSLIdeModule {
}
