/*
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.parser.antlr;

import com.google.inject.Inject;
import de.shashwat.xtext.homeauto.parser.antlr.internal.InternalRuleDSLParser;
import de.shashwat.xtext.homeauto.services.RuleDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RuleDSLParser extends AbstractAntlrParser {

	@Inject
	private RuleDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRuleDSLParser createParser(XtextTokenStream stream) {
		return new InternalRuleDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RuleDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RuleDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
