/**
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.ui;

import de.shashwat.xtext.homeauto.ui.AbstractRuleDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RuleDSLUiModule extends AbstractRuleDSLUiModule {
  public RuleDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
