/*
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.ui.tests;

import com.google.inject.Injector;
import de.shashwat.xtext.homeauto.ui.internal.HomeautoActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RuleDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HomeautoActivator.getInstance().getInjector("de.shashwat.xtext.homeauto.RuleDSL");
	}

}
