/*
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.ui;

import com.google.inject.Injector;
import de.shashwat.xtext.homeauto.ui.internal.HomeautoActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RuleDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(HomeautoActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		HomeautoActivator activator = HomeautoActivator.getInstance();
		return activator != null ? activator.getInjector(HomeautoActivator.DE_SHASHWAT_XTEXT_HOMEAUTO_RULEDSL) : null;
	}

}
