/**
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.scoping;

import de.shashwat.xtext.homeauto.scoping.AbstractRuleDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class RuleDSLScopeProvider extends AbstractRuleDSLScopeProvider {
}
