/*
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link RuleDSLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractRuleDSLWebModule extends DefaultWebModule {

}
