/**
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.web;

import de.shashwat.xtext.homeauto.web.AbstractRuleDSLWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class RuleDSLWebModule extends AbstractRuleDSLWebModule {
}
