/**
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.shashwat.xtext.homeauto.RuleDSLRuntimeModule;
import de.shashwat.xtext.homeauto.RuleDSLStandaloneSetup;
import de.shashwat.xtext.homeauto.ide.RuleDSLIdeModule;
import de.shashwat.xtext.homeauto.web.RuleDSLWebModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class RuleDSLWebSetup extends RuleDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    RuleDSLRuntimeModule _ruleDSLRuntimeModule = new RuleDSLRuntimeModule();
    RuleDSLIdeModule _ruleDSLIdeModule = new RuleDSLIdeModule();
    RuleDSLWebModule _ruleDSLWebModule = new RuleDSLWebModule();
    return Guice.createInjector(Modules2.mixin(_ruleDSLRuntimeModule, _ruleDSLIdeModule, _ruleDSLWebModule));
  }
}
