/**
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto;

import de.shashwat.xtext.homeauto.RuleDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RuleDSLStandaloneSetup extends RuleDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new RuleDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
