/**
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto;

import de.shashwat.xtext.homeauto.AbstractRuleDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RuleDSLRuntimeModule extends AbstractRuleDSLRuntimeModule {
}
