/*
 * generated by Xtext 2.18.0.M3
 */
package de.shashwat.xtext.homeauto


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RuleDSLStandaloneSetup extends RuleDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new RuleDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
